### ISSUE TITLE
Updated checkSum func causes arithmetic overflow

### ISSUE THREAD

**Issue by gierunio** [ampirator/EANBarcodeGenerator#12]
When attempting to generate a barcode image for `9930423979939`, I get the ```Swift runtime failure: arithmetic overflow compile flag``` runtime error. It is caused in the 265th line of the `CIEANBarcodeGenerator` class (where the `calculatedCheckdigit` is computed).

**Comment by MihaiLaur1996** [comment]
I’ve also encountered an issue with this library at the same function. Provided a version using this library and the next days hundreds of crashes reported.

**Comment by ampirator** [comment]
Hi!
Arithmetic overflow was fixed v 0.3.2.
