### ISSUE TITLE
Unable to generate UPC-A barcodes for some upc?

### ISSUE THREAD

**Issue by venkatraor** [ampirator/EANBarcodeGenerator#2]
I am unable to generate UPC-A barcode for this UPC "725272730706". It has a valid checkdigit and I am able to generate barcode for this upc in some websites like "https://barcode.tec-it.com/en/UPCA?data=72527273070".  Can you please suggest any solution for this?

Thanks

**Comment by ampirator** [comment]
Hi. I am using EAN-13 barcodes Format therefore to generate UPC-A you should add lead 0 to your code and barcode should be same as UPC-A
e.g. 0725272730706

**Comment by ampirator** [comment]
@venkatraor did it help you ?
