### ISSUE TITLE
'init(source:)' was deprecated in iOS 12.0: Core Image Kernel Language API deprecated.

### ISSUE THREAD

**Issue by miniapps-ios** [ampirator/EANBarcodeGenerator#6]
After updating to Xcode 12, I got this warning when building

'init(source:)' was deprecated in iOS 12.0: Core Image Kernel Language API deprecated.

Is there any way to fix the warning?

thank

**Comment by ampirator** [comment]
Hi, as describing in DOC  "Define CI_SILENCE_GL_DEPRECATION to silence these warnings"
But in general CIFilter should be reimplemeted via Metal Shading Language
